export const requestData = {
    columns: [
      { label: "ID", field: "id" },
      { label: "Request", field: "requestName" },
      { label: "Unit Name", field: "unitName" },
      { label: "Tenant", field: "tenantName" },
      { label: "Landlord", field: "landlordName" },
      { label: "Status", field: "requestStatus" },
      { label: "Date", field: "requestDate" },
    ],
    rows: [
      {
        id: 1,
        requestName: "Kitchen Maintainance",
        unitName: "Room 221",
        tenantName: "Jack",
        landlordName: "Kevin",
        requestDate: "2021-05-14",
        requestStatus: "Completed",
      },
      {
        id: 2,
        requestName: "Need another light source",
        unitName: "Room 224",
        tenantName: "Jose",
        landlordName: "Kevin",
        requestDate: "2021-05-14",
        requestStatus: "Processing",
      },
      {
        id: 3,
        requestName: "Fan not working",
        unitName: "Room 215",
        tenantName: "Rowen",
        landlordName: "Kevin",
        requestDate: "2021-05-14",
        requestStatus: "Pending",
      },
      {
        id: 4,
        requestName: "Need coffee",
        unitName: "Room 293",
        tenantName: "Jisnad",
        landlordName: "Kevin",
        requestDate: "2021-05-14",
        requestStatus: "Processing",
      },
    ],
  }