export const FETCH_CARD_DATA = "FETCH_CARD_DATA"
export const UPDATE_CARD_DATA = "UPDATE_CARD_DATA"

export const FETCH_RECENT_TRANSACTIONS = "FETCH_RECENT_TRANSACTIONS"
export const UPDATE_RECENT_TRANSACTIONS="UPDATE_RECENT_TRANSACTIONS"

export const FETCH_SOON_TO_BE_EXPIRED_LIST = "FETCH_SOON_TO_BE_EXPIRED_LIST"
export const UPDATE_SOON_TO_BE_EXPIRED_LIST = "UPDATE_SOON_TO_BE_EXPIRED_LIST"

export const FETCH_ATTENDANCE_STATUS = "FETCH_ATTENDANCE_STATUS"
export const UPDATE_ATTENDANCE_STATUS = "UPDATE_ATTENDANCE_STATUS"
export const CREATE_ATTENDANCE_STATUS = "CREATE_ATTENDANCE_STATUS"


export const API_ERROR_DASHBOARD = "API_ERROR_DASHBOARD"
export const CLEAR_ERROR_DASHBOARD = "CLEAR_ERROR_DASHBOARD"

export const BEGIN_LOADING_DASHBOARD = "BEGIN_LOADING_DASHBOARD"
export const END_LOADING_DASHBOARD = "END_LOADING_DASHBOARD"