//Fetch category List
export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST"
export const UPDATE_CATEGORY_LIST = "UPDATE_CATEGORY_LIST"

//fetch sub category list
export const FETCH_SUB_CATEGORY_LIST = "FETCH_SUB_CATEGORY_LIST"
export const UPDATE_SUB_CATEGORY_LIST="UPDATE_SUB_CATEGORY_LIST"

//error
export const CATEGORY_API_ERROR = "CATEGORY_API_ERROR"
export const CLEAR_CATEGORY_ERROR="CLEAR_CATEGORY_ERROR"