//Fetch List
export const FETCH_PROPERTY_LIST = "FETCH_PROPERTY_LIST"
export const UPDATE_PROPERTY_LIST = "UPDATE_PROPERTY_LIST"
export const API_ERROR_PROPERTIES = "API_ERROR_PROPERTIES"

//delete property
export const DELETE_PROPERTY = "DELETE_PROPERTY"
export const DELETE_PROPERTY_SUCCESS="DELETE_PROPERTY_SUCCESS"

//Fetch Details
export const FETCH_PROPERTY_DETAILS = "FETCH_PROPERTY_DETAILS"
export const UPDATE_PROPERTY_DETAILS = "UPDATE_PROPERTY_DETAILS"

//add property
export const ADD_PROPERTY = "ADD_PROPERTY"


//property staffs
export const FETCH_PROPERTY_STAFF = "FETCH_PROPERTY_STAFF"
export const UPDATE_PROPERTY_STAFF = "UPDATE_PROPERTY_STAFF"
export const ADD_PROPERTY_STAFF = "ADD_PROPERTY_STAFF"
export const ASSIGN_PROPERTY_STAFF = "ASSIGN_PROPERTY_STAFF"

export const FETCH_PROPERTY_TRANSACTIONS = "FETCH_PROPERTY_TRANSACTIONS"
export const UPDATE_PROPERTY_TRANSACTIONS = "UPDATE_PROPERTY_TRANSACTIONS"

export const FETCH_PROPERTY_TENANTS = "FETCH_PROPERTY_TENANTS"
export const UPDATE_PROPERTY_TENANTS = "UPDATE_PROPERTY_TENANTS"

export const FETCH_PROPERTY_DETAILS_CARD_DATA = "FETCH_PROPERTY_DETAILS_CARD_DATA"
export const UPDATE_PROPERTY_DETAILS_CARD_DATA = "UPDATE_PROPERTY_DETAILS_CARD_DATA"

export const FETCH_PROPERTY_TRANSACTION_CARD_DATA = "FETCH_PROPERTY_TRANSACTION_CARD_DATA"
export const UPDATE_PROPERTY_TRANSACTION_CARD_DATA = "UPDATE_PROPERTY_TRANSACTION_CARD_DATA"

export const SQUARE_OFF_RENT_DATA = "SQUARE_OFF_RENT_DATA"
export const SQRF_ERROR = "SQRF_ERROR"
export const CLEAR_SQRF_ERROR = "CLEAR_SQRF_ERROR"

export const FETCH_INCOME_CATEGORIES = "FETCH_INCOME_CATEGORIES"
export const UPDATE_INCOME_CATEGORIES = "UPDATE_INCOME_CATEGORIES"

export const FETCH_EXPENSE_CATEGORIES = "FETCH_EXPENSE_CATEGORIES"
export const UPDATE_EXPENSE_CATEGORIES = "UPDATE_EXPENSE_CATEGORIES"

export const CREATE_PROPERTY_TRANSACTION = "CREATE_PROPERTY_TRANSACTION"

//clear error
export const CLEAR_ERROR_PROPERTIES="CLEAR_ERROR_PROPERTIES"

export const BEGIN_LOADING = "BEGIN_LOADING"
export const END_LOADING = "END_LOADING"

