//Fetch List
export const FETCH_TENANT_LIST = "FETCH_TENANT_LIST"
export const UPDATE_TENANT_LIST = "UPDATE_TENANT_LIST"

export const API_ERROR_TENANTS = "API_ERROR_TENANTS"


//Fetch Details
export const FETCH_TENANT_DETAILS = "FETCH_TENANT_DETAILS"
export const UPDATE_TENANT_DETAILS = "UPDATE_TENANT_DETAILS"

export const FETCH_TENANT_PROFILE = "FETCH_TENANT_PROFILE"
export const UPDATE_TENANT_PROFILE = "UPDATE_TENANT_PROFILE"

export const FETCH_TENANT_TRANSACTIONS = "FETCH_TENANT_TRANSACTIONS"
export const UPDATE_TENANT_TRANSACTIONS = "UPDATE_TENANT_TRANSACTIONS"

export const CLEAR_TENANT_DETAILS = "CLEAR_TENANT_DETAILS"

export const FETCH_RENTED_UNITS = "FETCH_RENTED_UNITS"
export const UPDATE_RENTED_UNITS = "UPDATE_RENTED_UNITS"

//add property
export const ADD_TENANT = "ADD_TENANT"

//create rental
export const CREATE_RENTAL_TENANT = "CREATE_RENTAL_TENANT"

//delete tenant
export const DELETE_TENANT = "DELETE_TENANT"
export const DELETE_TENANT_SUCCESS="DELETE_TENANT_SUCCESS"

//clear error
export const CLEAR_ERROR="CLEAR_ERROR"

export const BEGIN_LOADING_TENANTS = "BEGIN_LOADING_TENANTS"
export const END_LOADING_TENANTS = "END_LOADING_TENANTS"

