export const FETCH_SUMMARY_LIST = "FETCH_SUMMARY_LIST"
export const UPDATE_SUMMARY_LIST = "UPDATE_SUMMARY_LIST"

export const FETCH_TRANSACTION_LIST = "FETCH_TRANSACTION_LIST"
export const UPDATE_TRANSACTION_LIST = "UPDATE_TRANSACTION_LIST"

export const FETCH_SUMMARY_CARD_DATA = "FETCH_SUMMARY_CARD_DATA"
export const UPDATE_SUMMARY_CARD_DATA = "UPDATE_SUMMARY_CARD_DATA"

export const API_ERROR_SUMMARY = "API_ERROR_SUMMARY"
export const CLEAR_SUMMARY_ERROR = "CLEAR_SUMMARY_ERROR"

export const BEGIN_SUMMARY_LOADING = "BEGIN_SUMMARY_LOADING"
export const END_SUMMARY_LOADING="END_SUMMARY_LOADING"